# Generated by Django 2.2.1 on 2019-07-10 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_model',
            field=models.CharField(max_length=10000, null=True, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='Is the user allowed to have access to be a buyer', verbose_name='I want to be a buyer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Is the user allowed to have access to the admin', verbose_name='I want to be a model provider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0x6d22F1c20D65e897f22CdBBc76b6D4df5483fA82', max_length=42),
        ),
    ]
