# Generated by Django 2.2.1 on 2019-07-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190710_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bought_model',
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0xAaB2b201f4EE9455ED2753aE4D2abD0fE93997aF', max_length=42),
        ),
    ]
