# Generated by Django 2.2.1 on 2019-07-14 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190711_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_model',
            field=models.CharField(default=[], max_length=10000, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0x49ab907F36506c6e6F235d9D132344Ca11BB5265', max_length=42),
        ),
    ]
