# Generated by Django 2.2.1 on 2019-07-14 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190714_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bought_model',
            field=models.CharField(default='', max_length=10000, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0xC728CB25214D08cD3492766918d899EE61074e85', max_length=42),
        ),
    ]
