# Generated by Django 2.1.2 on 2018-12-12 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='trainingData',
            field=models.FileField(default=django.utils.timezone.now, upload_to='ML_trainingData/'),
            preserve_default=False,
        ),
    ]
