# Generated by Django 2.1.3 on 2019-01-11 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0002_ml_model_trainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='label',
            field=models.FileField(default=django.utils.timezone.now, upload_to='ML_label/'),
            preserve_default=False,
        ),
    ]
