# Generated by Django 2.1.2 on 2019-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0003_ml_model_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='ml_model',
            name='split_data',
            field=models.IntegerField(default=0.2),
        ),
        migrations.AddField(
            model_name='ml_model',
            name='split_model',
            field=models.IntegerField(default=0.2),
        ),
    ]
