# Generated by Django 2.1.2 on 2019-05-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0004_auto_20190516_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='split_data',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='ml_model',
            name='split_model',
            field=models.FloatField(default=0.2),
        ),
    ]
