# Generated by Django 2.1.2 on 2019-05-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadModel', '0005_auto_20190516_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_model',
            name='split_model',
            field=models.FloatField(default=0.8),
        ),
    ]
