# Generated by Django 2.2.1 on 2019-06-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadData', '0002_auto_20190527_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='model_score',
            field=models.IntegerField(default=0),
        ),
    ]
